import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Export to PDF Utility - Feature #12
 * Export recommendations as PDF document
 */
export const exportRecommendationsToPDF = (recommendations, preferences) => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text('AalayaX Personalized Recommendations', 14, 22);
  
  // Add date
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })}`, 14, 30);
  
  // Add preferences summary
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text('Your Preferences:', 14, 42);
  
  doc.setFontSize(10);
  let yPos = 50;
  if (preferences.preferences && Array.isArray(preferences.preferences)) {
    preferences.preferences.forEach((pref, index) => {
      doc.text(`${index + 1}. Category: ${pref.category} | Budget: ₹${pref.budget} | Features: ${pref.featurePreference}`, 14, yPos);
      yPos += 6;
    });
  }
  
  yPos += 6;
  
  // Add recommendations table
  doc.setFontSize(14);
  doc.text('Recommendations:', 14, yPos);
  yPos += 8;
  
  const tableData = recommendations.map((item, index) => [
    index + 1,
    item.name || 'N/A',
    `₹${item.price?.toLocaleString('en-IN') || 'N/A'}`,
    item.rating ? `⭐${item.rating}/5` : 'N/A',
    item.category || 'N/A',
    `${item.matchScore || 0}%`
  ]);
  
  doc.autoTable({
    startY: yPos,
    head: [['#', 'Product Name', 'Price', 'Rating', 'Category', 'Match Score']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [15, 23, 42], // slate-900
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252] // slate-50
    },
    margin: { top: 10 },
  });
  
  // Add footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by AalayaX - Your AI Shopping Assistant`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  // Save the PDF
  doc.save(`AalayaX_Recommendations_${new Date().toISOString().split('T')[0]}.pdf`);
};

/**
 * Export comparison to PDF
 */
export const exportComparisonToPDF = (products) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.text('Product Comparison', 14, 22);
  
  doc.setFontSize(10);
  doc.text(`Compared on: ${new Date().toLocaleDateString('en-IN')}`, 14, 30);
  
  const tableData = [];
  const features = ['Name', 'Price', 'Rating', 'Category', 'Brand'];
  
  features.forEach(feature => {
    const row = [feature];
    products.forEach(product => {
      if (feature === 'Price') {
        row.push(`₹${product.price?.toLocaleString('en-IN') || 'N/A'}`);
      } else if (feature === 'Rating') {
        row.push(product.rating ? `${product.rating}/5` : 'N/A');
      } else {
        row.push(product[feature.toLowerCase()] || 'N/A');
      }
    });
    tableData.push(row);
  });
  
  doc.autoTable({
    startY: 40,
    head: [['Feature', ...products.map((p, i) => `Product ${i + 1}`)]],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255]
    }
  });
  
  doc.save(`AalayaX_Comparison_${new Date().toISOString().split('T')[0]}.pdf`);
};
